[package]
name = "hcl_deno"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
hcl-rs = "0.3.3"
serde_json = "1"
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1" }
wee_alloc = { version = "0.4" }

[profile.release]
opt-level = "s"
